- name: Install keybase
  when: ansible_os_family == 'Windows'
  win_chocolatey:
    name: keybase
    state: present

- name: Check for Keybase
  command: "keybase -v"
  changed_when: false
  check_mode: false
  ignore_errors: true
  register: keybase_result
  when: ansible_os_family != 'Windows'

- name: Download Keybase .deb
  when: ansible_os_family == "Debian" and keybase_result.rc != 0
  get_url:
    url: "{{ keybase_package_url }}/keybase_amd64.deb"
    dest: "{{ package_dest }}/keybase.deb"

- name: Start .deb install
  become: true
  when: ansible_os_family == "Debian" and keybase_result.rc != 0
  command: 'dpkg -i {{ package_dest }}/keybase.deb'
  register: install_result
  ignore_errors: true

- name: Finish .deb install
  become: true
  when: ansible_os_family == "Debian" and keybase_result.rc != 0 and install_result.rc != 0
  command: 'apt install -f --yes'

- name: Finish installation
  become: true
  when: ansible_os_family == "Debian" and keybase_result.rc != 0
  command: 'apt install -f -y'

- name: Install Keybase .rpm
  become: true
  when: ansible_os_family == "RedHat" and keybase_result.rc != 0
  package:
    name: "{{ keybase_package_url }}/keybase_amd64.rpm"

- name: Install Keybase.app
  when: ansible_os_family == "Darwin" and keybase_result.rc != 0
  become: false
  homebrew_cask:
    name: keybase
    state: present
    update_homebrew: yes
