---
- hosts: localhost
  vars:
    vm_output_dir: "{{ ansible_env.HOME }}/vm"
    images:
      - name: fedora31.qcow2
        url: https://download.fedoraproject.org/pub/fedora/linux/releases/31/Cloud/x86_64/images/Fedora-Cloud-Base-31-1.9.x86_64.qcow2
      # - name: fedora30.qcow2
      #   url: https://download.fedoraproject.org/pub/fedora/linux/releases/30/Cloud/x86_64/images/Fedora-Cloud-Base-30-1.2.x86_64.qcow2
  tasks:

    - name: install requirements
      pip:
        name:
          - libvirt-python
          - lxml
        extra_args: "--user"
        state: latest
      tags:
        - dependencies

    - name: define default bridge network
      virt_net:
        command: define
        name: default
        xml: /usr/share/libvirt/networks/default.xml
        state: active
      tags:
        - network


    - name: ensure vm dir
      file:
        name: "{{ vm_output_dir }}"
        state: directory

    - name: check presence of cloud images
      stat:
        path: "{{ vm_output_dir }}/{{ item.name }}"
      register: files
      loop: "{{ images }}"

    - name: download cloud images
      get_url:
        url: "{{ item.item.url }}"
        dest: "{{ vm_output_dir }}/{{ item.item.name }}"
      loop: "{{ files.results }}"
      when: not item.stat.exists
