---
- hosts: all
  tasks:
  - name: enable rpmfusion repos
    dnf:
      name:
      - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
      - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
      state: latest
    become: true

  - name: install exfat
    dnf:
      name: fuse-exfat
      state: latest
    become: true
