---
- name: Include OpenSuse vars
  include_vars: distribution_opensuse_leap.yaml

# - name: Add gcloud sdk repository
#   yum_repository:
#     name: google-cloud-sdk
#     description: GCloud SDK Upstream
#     baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
#     repo_gpgcheck: true
#     gpgcheck: true
#     gpgkey:
#       - 'https://packages.cloud.google.com/yum/doc/yum-key.gpg'
#       - 'https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'
#   become: true

- name: Install packages
  zypper:
    name: "{{ packages }}"
    state: latest
  become: true

- name: Install flatpak remotes
  flatpak_remote:
    name: "{{ item.name }}"
    flatpakrepo_url: "{{ item.flatpakrepo_url }}"
    state: present
    method: user
  loop: "{{ flatpak_remotes }}"

- name: Install flatpaks
  flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote is defined | ternary(item.remote, '') }}"
    state: present
    method: user
  loop: "{{ flatpak_packages }}"

- name: Upgrade packages
  zypper:
    name: '*'
    state: latest
  become: true

# - name: Configure sensors
#   template:
#     src: ../templates/custom.conf
#     dest: /etc/sensors.d/custom.conf
