---
dependencies: []

galaxy_info:
  author: Leon Allen
  description: Keybase application
  license: "license (MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Windows
      versions:
        - all
    - name: Darwin
      versions:
        - all
  galaxy_tags:
    - keybase
    - messaging
    - chat
