---
- hosts: all

  collections:
    - jtarasovic.kubernetes_tooling

  tasks:
    - name: Install host specific packages
      include_tasks: "tasks/install_{{ ansible_facts.distribution | lower }}.yaml"

    - name: Install pip packages
      pip:
        name:
          - ansible-lint
          - autopep8
          - awscli
          - docker
          - flake8
          - libvirt-python
          - lxml
          - molecule
          - psutil
          - pynvim
          - requests
          - yamllint
        extra_args: "--user"
        state: latest

    - name: Install keybase
      import_role:
        name: leonallen22.ansible_role_keybase

    - name: Install Go
      import_role:
        name: andrewrothstein.go

    # TODO: install specific version?
    # and/or figure out how to upgrade
    - name: Install kubectl
      import_role:
        name: andrewrothstein.kubectl

    - name: Install krew
      import_role:
        name: install_krew
      environment:
        PATH: "{{ ansible_env.HOME }}/.krew/bin:{{ ansible_env.PATH }}"

    - name: Install krew plugins
      krew:
        plugins:
          - access-matrix
          - ca-cert
          - ctx
          - debug
          - neat
          - outdated
          - rbac-lookup
          - rbac-view
          - ns
          - sniff
          - view-secret
          - whoami
          - who-can
      environment:
        PATH: "{{ ansible_env.HOME }}/.krew/bin:{{ ansible_env.PATH }}"

    - name: Install clusterctl
      import_role:
        name: install_clusterctl
      become: true

    - name: Install clusterawsadm
      import_role:
        name: install_clusterawsadm
      become: true

    - name: Install kustomize
      import_role:
        name: install_kustomize
      become: true

    - name: Install font(s)
      include_role:
        name: nerd-fonts
      vars:
        name: "{{ item.name }}"
        url: "{{ item.url }}"
      loop:
        # this kinda sucks
        - name: GoMonoNerdFontComplete.ttf
          url: "https://github.com/ryanoasis/nerd-fonts/raw/2.0.0/patched-fonts/Go-Mono/Regular/complete/Go%20Mono%20Nerd%20Font%20Complete.ttf"
        - name: GoMonoNerdFontCompleteMono.ttf
          url: "https://github.com/ryanoasis/nerd-fonts/raw/2.0.0/patched-fonts/Go-Mono/Regular/complete/Go%20Mono%20Nerd%20Font%20Complete%20Mono.ttf"

    - name: Install vscode-insiders
      import_role:
        name: vscode
      become: true
      vars:
        vscode_install: false
        vscode_insiders_install: true

    - name: Install vscode-insiders extensions
      import_role:
        name: vscode
      vars:
        vscode_install: false
        vscode_insiders_install: false
        vscode_extension:
          - alefragnani.Bookmarks
          - christian-kohler.npm-intellisense
          - CoenraadS.bracket-pair-colorizer
          - donjayamanne.githistory
          - esbenp.prettier-vscode
          - formulahendry.terminal
          - haaaad.ansible
          - ms-azuretools.vscode-docker
          - ms-vscode.Go
          - ms-python.python
          - octref.vetur
          - redhat.vscode-yaml
          - sdras.vue-vscode-extensionpack
          - sdras.vue-vscode-snippets
          - tombonnike.vscode-status-bar-format-toggle
          - VisualStudioExptTeam.vscodeintellicode
          - vscodevim.vim
          - wholroyd.jinja
          - xabikos.JavaScriptSnippets
