---
- hosts: all

  pre_tasks:
    - name: classify host by type of system
      group_by:
        key: "system_{{ ansible_facts.system | lower }}"
      tags:
        - always

    - name: classify host by distribution
      group_by:
        key: "distribution_{{ ansible_facts.distribution | lower }}"
        parents:
          - "system_{{ ansible_facts.system | lower }}"
      tags:
        - always


- import_playbook: install.yaml
- import_playbook: user.yaml
- import_playbook: configure_dotfiles.yaml
- import_playbook: configure_software.yaml

- hosts: distribution_fedora
  tasks:
    - name: configure gnome
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value | string }}"
        state: present
      loop: "{{ dconf }}"
      tags:
        - dconf
        - xkb
        - scroll

